import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import 'react-toastify/ReactToastify.min.css'

const poppins = Poppins({ subsets: ['latin'], weight: "300"})

export const metadata: Metadata = {
  title: 'Image Lite App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
